"use client";
import React, { Suspense } from "react";
import "./globals.sass";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import "../i18n";

interface RootLayoutProps {
  children: React.ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<h1>Loading...</h1>}>
          <Header />
          <main>{children}</main>
        </Suspense>
      </body>
    </html>
  );
};

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default RootLayout;
