import React from "react";
import "./globals.sass";
import { Inter } from "next/font/google";
import Header from "@/components/Header";

interface RootLayoutProps {
  children: React.ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default RootLayout;
