import React from "react";
import "./globals.sass";
import { Inter } from "next/font/google";

interface RootLayoutProps {
  children: React.ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default RootLayout;
